dist: focal

language: minimal

git:
  submodules: false

notifications:
  email: false

jobs:
  include:
    - stage: unit_tests
      os: linux
      language: go
      go:
        - 1.20.x
      script: bash go-test.sh -p pkg/zhmcclient
    
    - stage: vulnerbility_check
      os: linux
      language: go
      go:
        - 1.20.x
      script:
        - bash go-test.sh -v pkg/zhmcclient
stages:
- unit_tests
- vulnerbility_check